### ISSUE TITLE
Seems to prevent cleaning up instances when tearing down a pulumi stack

### ISSUE THREAD

**Issue by antifuchs** [MaterializeInc/k8s-eip-operator#15]
I think I found the reason why I had trouble tearing down my development pulumi stack (it would hang deleting k8s node groups): There were instances managed by the eip-operator running. The symptoms were:

* `pulumi destroy` hangs deleting a NodeGroup in a particular AZ
* EC2 instances in that stack exist in that AZ
* These instances have ENIs attached to them, with EIPs managed by eip-operator

Manually terminating the instances seems to do the trick, but it appears deleting the deployment of the operator needs to do some extra work de-associating the EIPs from its instances, or something (was @benesch's theory) (-:

I believe @zpu-materialize was affected by this as well, maybe he has done some additional digging.

**Comment by benesch** [comment]
I _think_ this should be good now. I spent a while running `pulumi up && pulumi destroy` over the weekend and didn't see any stacks get wedged like this!

**Comment by alex-hunt-materialize** [comment]
I'm pretty sure this is resolved now. I've done multiple destroy/up cycles without issue.
